### PR TITLE
Clear transaction after rollback to avoid rollbacked messages getting used in the next transaction

### PR DESCRIPTION
**Pull request by KayWu**
Issue #133

### CODE REVIEW

**Comment by ledoyen** [comment]
Hi @KayWu, thank you for spotting and fixing this !

Can you please squash the two commits into one so I can merge the PR ?

Thanks in advance

**Comment by KayWu** [comment]
Hi @ledoyen, I have squashed the two commits into one.
Thanks for reviewing.

**Comment by KayWu** [comment]
@ledoyen May I ask when is the next release?
I need to upgrade the lib once it releases.

**Comment by ledoyen** [comment]
@KayWu I just released a new version, it should be available in Maven Central within 2 hours.

**Comment by KayWu** [comment]
Many thanks.

**Pull request merged**
