### PR TITLE
Ability to register other types of exchange

### PR DESCRIPTION
**Pull request by jnbis**
This pull request lets you register other types of exchange at run time.

### CODE REVIEW

**Comment by ledoyen** [comment]
Welcome @jnbis and thanks for your proposal.

As **RabbitMQ** only defines 4 types of **Exchanges**, could you describe in details what you want to achieve with this modification ?

**Comment by ledoyen** [comment]
I was not aware of plugins supplying more exchange types, good to know :+1: 

Providing an extension point for adding custom exchanges could be a great way to unblock users needing exchange types from plugins that are not supported yet.

However as you mentionned 3 official plugins, don't you prefer to have these working out-of-the-box ?
_The point of this library afterall is for users to avoid coding mocking stuff and focus on the added value of integration tests._

These other teams you know, would they be kind enough to contribute their extensions ?

**Comment by jnbis** [comment]
Yes, I can try and put together another pull request with these implementations.

**Comment by ledoyen** [comment]
That would be awesome.

About the API of this proposal, even for tests, I am not confortable with using a `static` method for configuration, furthermore on a class that is not part of the "public API" if there was an explicit segregation.

How about a non-static configuration method on the `MockConnectionFactory` returning a `Configuration` object on which such a registration could be done ?

**Comment by jnbis** [comment]
Sounds good, let me work on it a little bit more and i will submit a different pull request

**Comment by ledoyen** [comment]
All thinks considered, it may be a little heavy to write.

It would be great to able to write something like
```java
    ConnectionFactory connectionFactory = new MockConnectionFactory()
        .withAdditionalExchange(new DelayedExchange());
```

But for now your proposal is sufficient enough as building this "configuration API" will require to move things around.

**Comment by ledoyen** [comment]
See #33

**Pull request closed without merging**
